// Copyright 2025 Stereolabs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef ZED_BODY_PARTS_HPP_
#define ZED_BODY_PARTS_HPP_

#include <map>
#include <vector>

namespace rviz_plugin_zed_od
{
namespace displays
{

enum class BODY_18_PARTS
{
  NOSE = 0,
  NECK = 1,
  RIGHT_SHOULDER = 2,
  RIGHT_ELBOW = 3,
  RIGHT_WRIST = 4,
  LEFT_SHOULDER = 5,
  LEFT_ELBOW = 6,
  LEFT_WRIST = 7,
  RIGHT_HIP = 8,
  RIGHT_KNEE = 9,
  RIGHT_ANKLE = 10,
  LEFT_HIP = 11,
  LEFT_KNEE = 12,
  LEFT_ANKLE = 13,
  RIGHT_EYE = 14,
  LEFT_EYE = 15,
  RIGHT_EAR = 16,
  LEFT_EAR = 17,
  LAST = 18
};

enum class BODY_34_PARTS
{
  PELVIS = 0,
  NAVAL_SPINE = 1,
  CHEST_SPINE = 2,
  NECK = 3,
  LEFT_CLAVICLE = 4,
  LEFT_SHOULDER = 5,
  LEFT_ELBOW = 6,
  LEFT_WRIST = 7,
  LEFT_HAND = 8,
  LEFT_HANDTIP = 9,
  LEFT_THUMB = 10,
  RIGHT_CLAVICLE = 11,
  RIGHT_SHOULDER = 12,
  RIGHT_ELBOW = 13,
  RIGHT_WRIST = 14,
  RIGHT_HAND = 15,
  RIGHT_HANDTIP = 16,
  RIGHT_THUMB = 17,
  LEFT_HIP = 18,
  LEFT_KNEE = 19,
  LEFT_ANKLE = 20,
  LEFT_FOOT = 21,
  RIGHT_HIP = 22,
  RIGHT_KNEE = 23,
  RIGHT_ANKLE = 24,
  RIGHT_FOOT = 25,
  HEAD = 26,
  NOSE = 27,
  LEFT_EYE = 28,
  LEFT_EAR = 29,
  RIGHT_EYE = 30,
  RIGHT_EAR = 31,
  LEFT_HEEL = 32,
  RIGHT_HEEL = 33,
  LAST = 34
};

enum class BODY_38_PARTS
{
  PELVIS = 0,
  SPINE_1 = 1,
  SPINE_2 = 2,
  SPINE_3 = 3,
  NECK = 4,
  NOSE = 5,
  LEFT_EYE = 6,
  RIGHT_EYE = 7,
  LEFT_EAR = 8,
  RIGHT_EAR = 9,
  LEFT_CLAVICLE = 10,
  RIGHT_CLAVICLE = 11,
  LEFT_SHOULDER = 12,
  RIGHT_SHOULDER = 13,
  LEFT_ELBOW = 14,
  RIGHT_ELBOW = 15,
  LEFT_WRIST = 16,
  RIGHT_WRIST = 17,
  LEFT_HIP = 18,
  RIGHT_HIP = 19,
  LEFT_KNEE = 20,
  RIGHT_KNEE = 21,
  LEFT_ANKLE = 22,
  RIGHT_ANKLE = 23,
  LEFT_BIG_TOE = 24,
  RIGHT_BIG_TOE = 25,
  LEFT_SMALL_TOE = 26,
  RIGHT_SMALL_TOE = 27,
  LEFT_HEEL = 28,
  RIGHT_HEEL = 29,
  // Hands
  LEFT_HAND_THUMB_4 = 30,  // tip
  RIGHT_HAND_THUMB_4 = 31,
  LEFT_HAND_INDEX_1 = 32,  // knuckle
  RIGHT_HAND_INDEX_1 = 33,
  LEFT_HAND_MIDDLE_4 = 34,  // tip
  RIGHT_HAND_MIDDLE_4 = 35,
  LEFT_HAND_PINKY_1 = 36,  // knuckle
  RIGHT_HAND_PINKY_1 = 37,
  ///@cond SHOWHIDDEN
  LAST = 38
    ///@endcond
};

enum class BODY_70_PARTS
{
  PELVIS = 0,
  SPINE_1 = 1,
  SPINE_2 = 2,
  SPINE_3 = 3,
  NECK = 4,
  NOSE = 5,
  LEFT_EYE = 6,
  RIGHT_EYE = 7,
  LEFT_EAR = 8,
  RIGHT_EAR = 9,
  LEFT_CLAVICLE = 10,
  RIGHT_CLAVICLE = 11,
  LEFT_SHOULDER = 12,
  RIGHT_SHOULDER = 13,
  LEFT_ELBOW = 14,
  RIGHT_ELBOW = 15,
  LEFT_WRIST = 16,
  RIGHT_WRIST = 17,
  LEFT_HIP = 18,
  RIGHT_HIP = 19,
  LEFT_KNEE = 20,
  RIGHT_KNEE = 21,
  LEFT_ANKLE = 22,
  RIGHT_ANKLE = 23,
  LEFT_BIG_TOE = 24,
  RIGHT_BIG_TOE = 25,
  LEFT_SMALL_TOE = 26,
  RIGHT_SMALL_TOE = 27,
  LEFT_HEEL = 28,
  RIGHT_HEEL = 29,
  // Hands
  // Left
  LEFT_HAND_THUMB_1 = 30,
  LEFT_HAND_THUMB_2 = 31,
  LEFT_HAND_THUMB_3 = 32,
  LEFT_HAND_THUMB_4 = 33,  // tip
  LEFT_HAND_INDEX_1 = 34,  // knuckle
  LEFT_HAND_INDEX_2 = 35,
  LEFT_HAND_INDEX_3 = 36,
  LEFT_HAND_INDEX_4 = 37,  // tip
  LEFT_HAND_MIDDLE_1 = 38,
  LEFT_HAND_MIDDLE_2 = 39,
  LEFT_HAND_MIDDLE_3 = 40,
  LEFT_HAND_MIDDLE_4 = 41,
  LEFT_HAND_RING_1 = 42,
  LEFT_HAND_RING_2 = 43,
  LEFT_HAND_RING_3 = 44,
  LEFT_HAND_RING_4 = 45,
  LEFT_HAND_PINKY_1 = 46,
  LEFT_HAND_PINKY_2 = 47,
  LEFT_HAND_PINKY_3 = 48,
  LEFT_HAND_PINKY_4 = 49,
  // Right
  RIGHT_HAND_THUMB_1 = 50,
  RIGHT_HAND_THUMB_2 = 51,
  RIGHT_HAND_THUMB_3 = 52,
  RIGHT_HAND_THUMB_4 = 53,
  RIGHT_HAND_INDEX_1 = 54,
  RIGHT_HAND_INDEX_2 = 55,
  RIGHT_HAND_INDEX_3 = 56,
  RIGHT_HAND_INDEX_4 = 57,
  RIGHT_HAND_MIDDLE_1 = 58,
  RIGHT_HAND_MIDDLE_2 = 59,
  RIGHT_HAND_MIDDLE_3 = 60,
  RIGHT_HAND_MIDDLE_4 = 61,
  RIGHT_HAND_RING_1 = 62,
  RIGHT_HAND_RING_2 = 63,
  RIGHT_HAND_RING_3 = 64,
  RIGHT_HAND_RING_4 = 65,
  RIGHT_HAND_PINKY_1 = 66,
  RIGHT_HAND_PINKY_2 = 67,
  RIGHT_HAND_PINKY_3 = 68,
  RIGHT_HAND_PINKY_4 = 69,
  LAST = 70
};

const std::vector<std::pair<BODY_18_PARTS, BODY_18_PARTS>> BODY_18_BONES{
  {BODY_18_PARTS::NOSE, BODY_18_PARTS::NECK},
  {BODY_18_PARTS::NECK, BODY_18_PARTS::RIGHT_SHOULDER},
  {BODY_18_PARTS::RIGHT_SHOULDER, BODY_18_PARTS::RIGHT_ELBOW},
  {BODY_18_PARTS::RIGHT_ELBOW, BODY_18_PARTS::RIGHT_WRIST},
  {BODY_18_PARTS::NECK, BODY_18_PARTS::LEFT_SHOULDER},
  {BODY_18_PARTS::LEFT_SHOULDER, BODY_18_PARTS::LEFT_ELBOW},
  {BODY_18_PARTS::LEFT_ELBOW, BODY_18_PARTS::LEFT_WRIST},
  {BODY_18_PARTS::RIGHT_SHOULDER, BODY_18_PARTS::RIGHT_HIP},
  {BODY_18_PARTS::RIGHT_HIP, BODY_18_PARTS::RIGHT_KNEE},
  {BODY_18_PARTS::RIGHT_KNEE, BODY_18_PARTS::RIGHT_ANKLE},
  {BODY_18_PARTS::LEFT_SHOULDER, BODY_18_PARTS::LEFT_HIP},
  {BODY_18_PARTS::LEFT_HIP, BODY_18_PARTS::LEFT_KNEE},
  {BODY_18_PARTS::LEFT_KNEE, BODY_18_PARTS::LEFT_ANKLE},
  {BODY_18_PARTS::RIGHT_SHOULDER, BODY_18_PARTS::LEFT_SHOULDER},
  {BODY_18_PARTS::RIGHT_HIP, BODY_18_PARTS::LEFT_HIP},
  {BODY_18_PARTS::NOSE, BODY_18_PARTS::RIGHT_EYE},
  {BODY_18_PARTS::RIGHT_EYE, BODY_18_PARTS::RIGHT_EAR},
  {BODY_18_PARTS::NOSE, BODY_18_PARTS::LEFT_EYE},
  {BODY_18_PARTS::LEFT_EYE, BODY_18_PARTS::LEFT_EAR}};

const std::vector<std::pair<BODY_34_PARTS, BODY_34_PARTS>> BODY_34_BONES{
  {BODY_34_PARTS::PELVIS, BODY_34_PARTS::NAVAL_SPINE},
  {BODY_34_PARTS::NAVAL_SPINE, BODY_34_PARTS::CHEST_SPINE},
  {BODY_34_PARTS::CHEST_SPINE, BODY_34_PARTS::LEFT_CLAVICLE},
  {BODY_34_PARTS::LEFT_CLAVICLE, BODY_34_PARTS::LEFT_SHOULDER},
  {BODY_34_PARTS::LEFT_SHOULDER, BODY_34_PARTS::LEFT_ELBOW},
  {BODY_34_PARTS::LEFT_ELBOW, BODY_34_PARTS::LEFT_WRIST},
  {BODY_34_PARTS::LEFT_WRIST, BODY_34_PARTS::LEFT_HAND},
  {BODY_34_PARTS::LEFT_HAND, BODY_34_PARTS::LEFT_HANDTIP},
  {BODY_34_PARTS::LEFT_WRIST, BODY_34_PARTS::LEFT_THUMB},
  {BODY_34_PARTS::CHEST_SPINE, BODY_34_PARTS::RIGHT_CLAVICLE},
  {BODY_34_PARTS::RIGHT_CLAVICLE, BODY_34_PARTS::RIGHT_SHOULDER},
  {BODY_34_PARTS::RIGHT_SHOULDER, BODY_34_PARTS::RIGHT_ELBOW},
  {BODY_34_PARTS::RIGHT_ELBOW, BODY_34_PARTS::RIGHT_WRIST},
  {BODY_34_PARTS::RIGHT_WRIST, BODY_34_PARTS::RIGHT_HAND},
  {BODY_34_PARTS::RIGHT_HAND, BODY_34_PARTS::RIGHT_HANDTIP},
  {BODY_34_PARTS::RIGHT_WRIST, BODY_34_PARTS::RIGHT_THUMB},
  {BODY_34_PARTS::PELVIS, BODY_34_PARTS::LEFT_HIP},
  {BODY_34_PARTS::LEFT_HIP, BODY_34_PARTS::LEFT_KNEE},
  {BODY_34_PARTS::LEFT_KNEE, BODY_34_PARTS::LEFT_ANKLE},
  {BODY_34_PARTS::LEFT_ANKLE, BODY_34_PARTS::LEFT_FOOT},
  {BODY_34_PARTS::PELVIS, BODY_34_PARTS::RIGHT_HIP},
  {BODY_34_PARTS::RIGHT_HIP, BODY_34_PARTS::RIGHT_KNEE},
  {BODY_34_PARTS::RIGHT_KNEE, BODY_34_PARTS::RIGHT_ANKLE},
  {BODY_34_PARTS::RIGHT_ANKLE, BODY_34_PARTS::RIGHT_FOOT},
  {BODY_34_PARTS::CHEST_SPINE, BODY_34_PARTS::NECK},
  {BODY_34_PARTS::NECK, BODY_34_PARTS::HEAD},
  {BODY_34_PARTS::HEAD, BODY_34_PARTS::NOSE},
  {BODY_34_PARTS::NOSE, BODY_34_PARTS::LEFT_EYE},
  {BODY_34_PARTS::LEFT_EYE, BODY_34_PARTS::LEFT_EAR},
  {BODY_34_PARTS::NOSE, BODY_34_PARTS::RIGHT_EYE},
  {BODY_34_PARTS::RIGHT_EYE, BODY_34_PARTS::RIGHT_EAR},
  {BODY_34_PARTS::LEFT_ANKLE, BODY_34_PARTS::LEFT_HEEL},
  {BODY_34_PARTS::RIGHT_ANKLE, BODY_34_PARTS::RIGHT_HEEL},
  {BODY_34_PARTS::LEFT_HEEL, BODY_34_PARTS::LEFT_FOOT},
  {BODY_34_PARTS::RIGHT_HEEL, BODY_34_PARTS::RIGHT_FOOT}};

const std::vector<std::pair<BODY_38_PARTS, BODY_38_PARTS>> BODY_38_BONES{
  {BODY_38_PARTS::PELVIS, BODY_38_PARTS::SPINE_1},
  {BODY_38_PARTS::SPINE_1, BODY_38_PARTS::SPINE_2},
  {BODY_38_PARTS::SPINE_2, BODY_38_PARTS::SPINE_3},
  {BODY_38_PARTS::SPINE_3, BODY_38_PARTS::NECK},
  // Face
  {BODY_38_PARTS::NECK, BODY_38_PARTS::NOSE},
  {BODY_38_PARTS::NOSE, BODY_38_PARTS::LEFT_EYE},
  {BODY_38_PARTS::LEFT_EYE, BODY_38_PARTS::LEFT_EAR},
  {BODY_38_PARTS::NOSE, BODY_38_PARTS::RIGHT_EYE},
  {BODY_38_PARTS::RIGHT_EYE, BODY_38_PARTS::RIGHT_EAR},
  // Left arm
  {BODY_38_PARTS::SPINE_3, BODY_38_PARTS::LEFT_CLAVICLE},
  {BODY_38_PARTS::LEFT_CLAVICLE, BODY_38_PARTS::LEFT_SHOULDER},
  {BODY_38_PARTS::LEFT_SHOULDER, BODY_38_PARTS::LEFT_ELBOW},
  {BODY_38_PARTS::LEFT_ELBOW, BODY_38_PARTS::LEFT_WRIST},
  {BODY_38_PARTS::LEFT_WRIST, BODY_38_PARTS::LEFT_HAND_THUMB_4},
  {BODY_38_PARTS::LEFT_WRIST, BODY_38_PARTS::LEFT_HAND_INDEX_1},
  {BODY_38_PARTS::LEFT_WRIST, BODY_38_PARTS::LEFT_HAND_MIDDLE_4},
  {BODY_38_PARTS::LEFT_WRIST, BODY_38_PARTS::LEFT_HAND_PINKY_1},
  // Right arm
  {BODY_38_PARTS::SPINE_3, BODY_38_PARTS::RIGHT_CLAVICLE},
  {BODY_38_PARTS::RIGHT_CLAVICLE, BODY_38_PARTS::RIGHT_SHOULDER},
  {BODY_38_PARTS::RIGHT_SHOULDER, BODY_38_PARTS::RIGHT_ELBOW},
  {BODY_38_PARTS::RIGHT_ELBOW, BODY_38_PARTS::RIGHT_WRIST},
  {BODY_38_PARTS::RIGHT_WRIST, BODY_38_PARTS::RIGHT_HAND_THUMB_4},
  {BODY_38_PARTS::RIGHT_WRIST, BODY_38_PARTS::RIGHT_HAND_INDEX_1},
  {BODY_38_PARTS::RIGHT_WRIST, BODY_38_PARTS::RIGHT_HAND_MIDDLE_4},
  {BODY_38_PARTS::RIGHT_WRIST, BODY_38_PARTS::RIGHT_HAND_PINKY_1},
  // Left leg
  {BODY_38_PARTS::PELVIS, BODY_38_PARTS::LEFT_HIP},
  {BODY_38_PARTS::LEFT_HIP, BODY_38_PARTS::LEFT_KNEE},
  {BODY_38_PARTS::LEFT_KNEE, BODY_38_PARTS::LEFT_ANKLE},
  {BODY_38_PARTS::LEFT_ANKLE, BODY_38_PARTS::LEFT_HEEL},
  {BODY_38_PARTS::LEFT_ANKLE, BODY_38_PARTS::LEFT_BIG_TOE},
  {BODY_38_PARTS::LEFT_ANKLE, BODY_38_PARTS::LEFT_SMALL_TOE},
  // Right leg
  {BODY_38_PARTS::PELVIS, BODY_38_PARTS::RIGHT_HIP},
  {BODY_38_PARTS::RIGHT_HIP, BODY_38_PARTS::RIGHT_KNEE},
  {BODY_38_PARTS::RIGHT_KNEE, BODY_38_PARTS::RIGHT_ANKLE},
  {BODY_38_PARTS::RIGHT_ANKLE, BODY_38_PARTS::RIGHT_HEEL},
  {BODY_38_PARTS::RIGHT_ANKLE, BODY_38_PARTS::RIGHT_BIG_TOE},
  {BODY_38_PARTS::RIGHT_ANKLE, BODY_38_PARTS::RIGHT_SMALL_TOE},
};

const std::vector<std::pair<BODY_70_PARTS, BODY_70_PARTS>> BODY_70_BONES{
  {BODY_70_PARTS::PELVIS, BODY_70_PARTS::SPINE_1},
  {BODY_70_PARTS::SPINE_1, BODY_70_PARTS::SPINE_2},
  {BODY_70_PARTS::SPINE_2, BODY_70_PARTS::SPINE_3},
  {BODY_70_PARTS::SPINE_3, BODY_70_PARTS::NECK},
  // Face
  {BODY_70_PARTS::NECK, BODY_70_PARTS::NOSE},
  {BODY_70_PARTS::NOSE, BODY_70_PARTS::LEFT_EYE},
  {BODY_70_PARTS::LEFT_EYE, BODY_70_PARTS::LEFT_EAR},
  {BODY_70_PARTS::NOSE, BODY_70_PARTS::RIGHT_EYE},
  {BODY_70_PARTS::RIGHT_EYE, BODY_70_PARTS::RIGHT_EAR},
  // Left arm
  {BODY_70_PARTS::SPINE_3, BODY_70_PARTS::LEFT_CLAVICLE},
  {BODY_70_PARTS::LEFT_CLAVICLE, BODY_70_PARTS::LEFT_SHOULDER},
  {BODY_70_PARTS::LEFT_SHOULDER, BODY_70_PARTS::LEFT_ELBOW},
  {BODY_70_PARTS::LEFT_ELBOW, BODY_70_PARTS::LEFT_WRIST},
  // Left hand
  {BODY_70_PARTS::LEFT_WRIST, BODY_70_PARTS::LEFT_HAND_THUMB_1},
  {BODY_70_PARTS::LEFT_WRIST, BODY_70_PARTS::LEFT_HAND_THUMB_2},
  {BODY_70_PARTS::LEFT_WRIST, BODY_70_PARTS::LEFT_HAND_THUMB_3},
  {BODY_70_PARTS::LEFT_WRIST, BODY_70_PARTS::LEFT_HAND_THUMB_4},
  {BODY_70_PARTS::LEFT_WRIST, BODY_70_PARTS::LEFT_HAND_INDEX_1},
  {BODY_70_PARTS::LEFT_WRIST, BODY_70_PARTS::LEFT_HAND_INDEX_2},
  {BODY_70_PARTS::LEFT_WRIST, BODY_70_PARTS::LEFT_HAND_INDEX_3},
  {BODY_70_PARTS::LEFT_WRIST, BODY_70_PARTS::LEFT_HAND_INDEX_4},
  {BODY_70_PARTS::LEFT_WRIST, BODY_70_PARTS::LEFT_HAND_MIDDLE_1},
  {BODY_70_PARTS::LEFT_WRIST, BODY_70_PARTS::LEFT_HAND_MIDDLE_2},
  {BODY_70_PARTS::LEFT_WRIST, BODY_70_PARTS::LEFT_HAND_MIDDLE_3},
  {BODY_70_PARTS::LEFT_WRIST, BODY_70_PARTS::LEFT_HAND_MIDDLE_4},
  {BODY_70_PARTS::LEFT_WRIST, BODY_70_PARTS::LEFT_HAND_PINKY_1},
  {BODY_70_PARTS::LEFT_WRIST, BODY_70_PARTS::LEFT_HAND_PINKY_2},
  {BODY_70_PARTS::LEFT_WRIST, BODY_70_PARTS::LEFT_HAND_PINKY_3},
  {BODY_70_PARTS::LEFT_WRIST, BODY_70_PARTS::LEFT_HAND_PINKY_4},
  // Right arm
  {BODY_70_PARTS::SPINE_3, BODY_70_PARTS::RIGHT_CLAVICLE},
  {BODY_70_PARTS::RIGHT_CLAVICLE, BODY_70_PARTS::RIGHT_SHOULDER},
  {BODY_70_PARTS::RIGHT_SHOULDER, BODY_70_PARTS::RIGHT_ELBOW},
  {BODY_70_PARTS::RIGHT_ELBOW, BODY_70_PARTS::RIGHT_WRIST},
  // Right hand
  {BODY_70_PARTS::RIGHT_WRIST, BODY_70_PARTS::RIGHT_HAND_THUMB_1},
  {BODY_70_PARTS::RIGHT_WRIST, BODY_70_PARTS::RIGHT_HAND_THUMB_2},
  {BODY_70_PARTS::RIGHT_WRIST, BODY_70_PARTS::RIGHT_HAND_THUMB_3},
  {BODY_70_PARTS::RIGHT_WRIST, BODY_70_PARTS::RIGHT_HAND_THUMB_4},
  {BODY_70_PARTS::RIGHT_WRIST, BODY_70_PARTS::RIGHT_HAND_INDEX_1},
  {BODY_70_PARTS::RIGHT_WRIST, BODY_70_PARTS::RIGHT_HAND_INDEX_2},
  {BODY_70_PARTS::RIGHT_WRIST, BODY_70_PARTS::RIGHT_HAND_INDEX_3},
  {BODY_70_PARTS::RIGHT_WRIST, BODY_70_PARTS::RIGHT_HAND_INDEX_4},
  {BODY_70_PARTS::RIGHT_WRIST, BODY_70_PARTS::RIGHT_HAND_MIDDLE_1},
  {BODY_70_PARTS::RIGHT_WRIST, BODY_70_PARTS::RIGHT_HAND_MIDDLE_2},
  {BODY_70_PARTS::RIGHT_WRIST, BODY_70_PARTS::RIGHT_HAND_MIDDLE_3},
  {BODY_70_PARTS::RIGHT_WRIST, BODY_70_PARTS::RIGHT_HAND_MIDDLE_4},
  {BODY_70_PARTS::RIGHT_WRIST, BODY_70_PARTS::RIGHT_HAND_PINKY_1},
  {BODY_70_PARTS::RIGHT_WRIST, BODY_70_PARTS::RIGHT_HAND_PINKY_2},
  {BODY_70_PARTS::RIGHT_WRIST, BODY_70_PARTS::RIGHT_HAND_PINKY_3},
  {BODY_70_PARTS::RIGHT_WRIST, BODY_70_PARTS::RIGHT_HAND_PINKY_4},
  // Left leg
  {BODY_70_PARTS::PELVIS, BODY_70_PARTS::LEFT_HIP},
  {BODY_70_PARTS::LEFT_HIP, BODY_70_PARTS::LEFT_KNEE},
  {BODY_70_PARTS::LEFT_KNEE, BODY_70_PARTS::LEFT_ANKLE},
  {BODY_70_PARTS::LEFT_ANKLE, BODY_70_PARTS::LEFT_HEEL},
  {BODY_70_PARTS::LEFT_ANKLE, BODY_70_PARTS::LEFT_BIG_TOE},
  {BODY_70_PARTS::LEFT_ANKLE, BODY_70_PARTS::LEFT_SMALL_TOE},
  // Right leg
  {BODY_70_PARTS::PELVIS, BODY_70_PARTS::RIGHT_HIP},
  {BODY_70_PARTS::RIGHT_HIP, BODY_70_PARTS::RIGHT_KNEE},
  {BODY_70_PARTS::RIGHT_KNEE, BODY_70_PARTS::RIGHT_ANKLE},
  {BODY_70_PARTS::RIGHT_ANKLE, BODY_70_PARTS::RIGHT_HEEL},
  {BODY_70_PARTS::RIGHT_ANKLE, BODY_70_PARTS::RIGHT_BIG_TOE},
  {BODY_70_PARTS::RIGHT_ANKLE, BODY_70_PARTS::RIGHT_SMALL_TOE},
};

}  // namespace displays
}  // namespace rviz_plugin_zed_od

#endif  // ZED_BODY_PARTS_HPP_
